services:
  - type: web
    name: iris-classification
    env: python
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "gunicorn iris:app"
    plan: free
